### ISSUE TITLE
Add throws declaration to methods

### ISSUE THREAD

**Issue by Acconut** [ifedapoolarewaju/transloadit-java-sdk#6]
The `throws` declaration helps a caller to be aware of which exceptions a method may throw and to prepare for these cases (see https://docs.oracle.com/javase/tutorial/essential/exceptions/declaring.html). This could be applied to `Transloadit#getSignature` as it may throw a RuntimeException from HmacSHA1 (https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Transloadit.java#L69) and also others.

In my setup, the IDE and compiler complain if I attempt to throw an undeclared exception. This helps one enormous to verify that this information are up-to-date.

**Comment by ifedapoolarewaju** [comment]
I have addressed this issue in most cases with the exemption of this [method](https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Transloadit.java#L77) because the code declares the algorithm internally and it's not expected to change. So the exception `NoSuchAlgorithmException` will never be thrown. Also it enforces the secret to a `StandardCharsets.UTF_8` so the `InvalidKeyException` will never be thrown either. Please  let me know what you think about this.

**Comment by Acconut** [comment]
You should still add the corresponding `throws` declaration the method you mentioned. Even thou you assume that these exception will never be thrown, the compilers and linters will not be aware of this and may complain. Generally, it's better to add too many exceptions to the declaration than too few. In particular, since changing the `throws` declaration is a breaking change according to the SemVer protocol in Java.

**Comment by ifedapoolarewaju** [comment]
@Acconut I have addressed this issue [here](https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/master/src/com/transloadit/sdk/Request.java#L152)
