### ISSUE TITLE
Reduce number of public attributes

### ISSUE THREAD

**Issue by Acconut** [ifedapoolarewaju/transloadit-java-sdk#8]
In Javaland you usually do not have attributes in a class which are public (e.g. https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/fcf06b7bbef86e5a565126efb73e4a4922a665b6/src/main/java/com/transloadit/sdk/response/AssemblyResponse.java#L13-L15) except there is a very good reason for. Instead you set them private (or protected or package-private) and add getter and optionally setter methods for them. This is preferred because it provides a more uniform interface, hides your inner structure and makes it possible to validate input data. If you don't want to type all those methods which is the case for me, look into how your IDE can auto-generate those. Eclipse and Android Studio/Intellij are guaranteed capable of this without any plugins.

**Comment by ifedapoolarewaju** [comment]
yes I agree. But I also want these attributes to be easily accessible and have the `AssemblyResponse` class serve as a model representation of an Assembly so it is more intuitive. So `assmebly.id` immediately means the `id` of the assembly. This is why I made the attribute `final` so it can't be altered.

**Comment by Acconut** [comment]
> But I also want these attributes to be easily accessible and have the AssemblyResponse class serve as a model representation of an Assembly so it is more intuitive. So assmebly.id immediately means the id of the assembly.

I don't see why `assembly.getId()` would be less expressive or intuitive than `assembly.id`. Both expression convey that their value will yield to the assemblies' ID.

> This is why I made the attribute final so it can't be altered.

This getter/setter pattern is not about preventing attributes from being modified but instead is about encapsulation aka hiding your internal state from the outside world (see https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)).

**Comment by ifedapoolarewaju** [comment]
Yes I understand that, but in this case the attributes (`id`, `url`, `sslUrl`) of the object `AssemblyResponse`  are solely built for the end user. Those attributes are not used internally by the `Transloadit-SDK`. So in order to retain encapsulation and data integrity, I propose changing the constructor from `public` to `package-private` [here](https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/fcf06b7bbef86e5a565126efb73e4a4922a665b6/src/main/java/com/transloadit/sdk/response/AssemblyResponse.java#L17).

A user has no business doing `new AssemblyResponse(...)`,
so it can be done only internally. Hence the object can only be instantiated internally and the attributes cannot be changed afterwards. What do you think?

I really think it is unnecessary to have `getters/setters` in this particular case, for these particular attributes since that is what they are specifically added in the first place. They are specifically added so the end user can easily access them.

**Comment by Acconut** [comment]
> A user has no business doing new AssemblyResponse(...),

That's not true for every situation. Imagine a unit test for your application where you want to ensure that your custom logic handles an AssemblyResponse properly. In this case, you actually want to use the constructor.

> I really think it is unnecessary to have getters/setters in this particular case, for these particular attributes since that is what they are specifically added in the first place. They are specifically added so the end user can easily access them.

I still disagree with you on this front but I also don't want to block the progress of this SDK. Just keep in mind that you cannot change attributes while you can always change the implementation of a getter method. Design an interface for the future not only the present.

**Comment by ifedapoolarewaju** [comment]
@Acconut alright, I have made the changes as suggested 👍 . [here](https://github.com/ifedapoolarewaju/transloadit-java-sdk/pull/9/commits/e4f0e8c457f8d4a59147a899ddc08361559f21df)

**Comment by ifedapoolarewaju** [comment]
@Acconut are we good to close this issue?

**Comment by Acconut** [comment]
Thank you for addressing this! You may also have a look at the ListResponse class (https://github.com/ifedapoolarewaju/transloadit-java-sdk/blob/e4f0e8c457f8d4a59147a899ddc08361559f21df/src/main/java/com/transloadit/sdk/response/ListResponse.java#L11-L12) before we finish this issue :)

**Comment by ifedapoolarewaju** [comment]
@Acconut fixed 👍
